#pragma config(Motor,  port2,           base,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           joint11,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           joint12,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           topjoint,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           bottumjoint,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           turnjoint,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 while(1==1)
	{
   motor[port2]=vexRT[Ch4Xmtr2]/2;
   motor[port3]=vexRT[ch3]/2;
   motor[port4]=vexRT[Ch3]/2;
   motor[port6]=vexRT[Ch2]/2;
   motor[port5]=vexRT[Ch2]/2
   motor[port7]=vexRT[Ch1Xmtr2]/2;

   		if(vexRT[Btn6U] == 1)
 		{
 			motor[port8] = 5;
 		}
 			else if(vexRT[Btn6D] == 1)
 		{
 			motor[port8] = -5;
 		}
 			else
 		{
 			motor[port8] = 0;
 		}
	}
}
